- name: Deploy Python DevOps App
  hosts: web
  tasks:
    - name: Pull latest image
      shell: docker pull python-devops-app

    - name: Stop old container
      shell: docker stop flask || true && docker rm flask || true

    - name: Run new container
      shell: docker run -d -p 80:5000 --name flask python-devops-app
